
#SI EXISTE LA BASE DE DATOS, SE BORRA EL CONTENIDO
DROP DATABASE IF EXISTS ecommerce;

#SI NO EXISTE LA BASE DE DATOS, SE CREA
CREATE DATABASE IF NOT EXISTS ecommerce 
	CHARACTER SET utf8mb4 
	COLLATE utf8mb4_general_ci;

#SE SELECCIONA LA BASE DE DATOS PARA POSTERIORMENTE CREAR LAS TABLAS
USE ecommerce;

#CREACION DE LAS TABLAS
CREATE TABLE IF NOT EXISTS producto (
	id BINARY(16) PRIMARY KEY NOT NULL,
	sku VARCHAR(255) NOT NULL,
	nombre VARCHAR(255) NOT NULL,
	precio FLOAT NOT NULL,
	descripcion VARCHAR(255) NOT NULL,
	marca BINARY(16) NOT NULL,
	categoria BINARY(16) NOT NULL,
	ancho FLOAT NOT NULL,
	alto FLOAT NOT NULL,
	profundidad FLOAT NOT NULL,
	peso FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario (
	id BINARY(16) PRIMARY KEY NOT NULL,
	nombre VARCHAR(255) NOT NULL,
	apellido VARCHAR(255) NOT NULL,
	direccion VARCHAR(255) NOT NULL,
	telefono VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	usuario VARCHAR(255) NOT NULL,
	clave VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS carrito (
	id BINARY(16) PRIMARY KEY NOT NULL,
	usuario_id BINARY(16) NOT NULL,
	producto_id BINARY(16) NOT NULL,
	cantidad int NOT NULL
);

CREATE TABLE IF NOT EXISTS stock (
	id BINARY(16) PRIMARY KEY NOT NULL,
	product_id BINARY(16) NOT NULL,
	stock int NOT NULL
);

CREATE TABLE IF NOT EXISTS marca (
	id BINARY(16) PRIMARY KEY NOT NULL,
	marca VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS categoria (
	id BINARY(16) PRIMARY KEY NOT NULL,
	categoria VARCHAR(255) NOT NULL
);